apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

 

metadata:
  name: sparta-mongo-db-deploy
  namespace: default

 

spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongo
  targetCPUUtilizationPercentage: 50