---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ryanjohal/tech241-sparta-app
        ports:
        - containerPort: 3000
        env:
            - name: DB_HOST
              value: mongodb://mongo:27017/posts
        imagePullPolicy: Always
    
      volumes:
        - name: node-pv   #Part to connect to PVC
          persistentVolumeClaim:
            claimName: node-pvc
